apiVersion: v1
kind: Service
metadata:
  name: resume-app
  namespace: resume-app
spec:
  selector:
    app: resume-app
  ports:
    - port: 80
      targetPort: 8080
      protocol: TCP
  type: ClusterIP
